### ISSUE TITLE
rename to go-multistream-select

### ISSUE THREAD

**Issue by daviddias** [multiformats/go-multistream#11]
as per https://github.com/multiformats/multicodec/pull/16#issuecomment-249497577

**Comment by whyrusleeping** [comment]
@diasdavid but thats such a long name...

**Comment by diasdavid** [comment]
![image](https://cloud.githubusercontent.com/assets/1211152/21070598/214a11ae-be3d-11e6-9d52-324f0c5d7f57.png)

**Comment by diasdavid** [comment]
Hey @multiformats/go-team, can we have this package renamed? Some of our users get confused by not finding go-multistream-select and thing this package is only the multistream spec and not the multistream-select one.

**Comment by lgierth** [comment]
By now we should just make a list of all the renames and to them at once, e.g. go-ws-transport, ipld/go-cid, etc.

**Comment by lgierth** [comment]
@diasdavid are you gonna rename railing to bootstrap? :):)

**Comment by whyrusleeping** [comment]
> @diasdavid are you gonna rename railing to bootstrap? :):)

Yeah, lets make a trade...

**Comment by diasdavid** [comment]
[FINE™](https://i.imgur.com/w5FNihJ.jpg)
