### ISSUE TITLE
Return protocol ID that is not supported in error message.

### ISSUE THREAD

**Issue by p-shahi** [multiformats/go-multistream#94]
Migrating https://github.com/libp2p/go-libp2p/issues/1988

> > It would be convenient if the protocol ID that is not supported by the remote peer is returned as well in the error message.
> > 
> > Current:
> > 
> > `protocol not supported`
> > 
> > Desired:
> > 
> > `protocol not supported: <protocol_ID>`
> >
> > @renaynay
> 
>
> Not opposed to it, but is this particularly useful? You know which protocol(s) you were trying to negotiate when you receive this error.
> 
> If we wanted to add the protocol IDs, we'd run into https://github.com/libp2p/go-libp2p/issues/1886 again.
> 
> This is a go-multistream issue, not a go-libp2p issue by the way. Moving it there.
>
> @marten-seemann

**Comment by renaynay** [comment]
@marten-seemann yes this is particularly useful when debugging on multiple networks or performing upgrades where we upgrade the protocolID.

**Comment by marten-seemann** [comment]
That doesn't answer my question. You can easily annotate the error yourself:
```go
str, err := host.NewStream(ctx, peerID, proto)
if err != nil {
     return fmt.Errorf("failed to open stream with proto %s: %w", proto, err)
}
```

**Comment by Wondertan** [comment]
Adding two cents here, @marten-seemann.

This is totally valid argument when you open or handle a new stream.
> You know which protocol(s) you were trying to negotiate when you receive this error.

However, in the system, when a high-level operation consisting of multiple subprotocols fails, the error "protocol not supported" requires going over each protocol to understand where it's coming from. Of course, one could wrap the error in each protocol with its name, but it's still better to do it in one place. Also, add on the top @renaynay's point above multiple different networks, which are appended as suffixes to the protocol id. In the end, debugging something like this starts to be painful and simple mitigation is to add the protocol name.

**Comment by marten-seemann** [comment]
That's a fair point. Want to submit a PR?

We should probably introduce an error type here, so you can get the list of protocols by using an error assertion. wdyt?
```go
type ErrNotSupport struct {
     Protos []string
}
```

**Comment by p-shahi** [comment]
@sukunrt are you interested in picking this up (other folks lmk if you've already started work on this)?
This would be a good quality of life change!

**Comment by sukunrt** [comment]
Yes I'd like to pick this up.

**Comment by sukunrt** [comment]
Here we need to change ```ErrNotSupported``` response to use a new type
```
type ErrNotSupport struct {
     Protos []string
}
```
which will include all the protocols which were not supported. 
This change will only impact client.go with methods like ```SelectOneOf```, right?

**Comment by marten-seemann** [comment]
I also see one usage in `doReadHandshake`, what about that one?

> Here we need to change `ErrNotSupported` response to use a new type
> 
> ```
> type ErrNotSupport struct {
>      Protos []string
> }
> ```

This would also need to be generic, right?

**Comment by sukunrt** [comment]
Yes. doReadHandshake will change. 

Agreed, ErrNotSupport should be generic otherwise it'll be a lot of string(proto).

**Comment by sukunrt** [comment]
```type ErrNotSupport struct {
     Protos []string
}```
@marten-seemann This type can be named ```ErrNotSupported[T]```, right?
